require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'ScanditCaptureCorePlugin' do
  capacitor_pods
end

target 'ScanditCaptureCorePluginTests' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
